[features]
seeds = false
skip-lint = false

[programs.devnet]
alyrasign = "5efYRoL5mJVBmnJCwTtEmtErLyMSAjjh3BW3ra2quKCP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "deployer-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/" 