[features]
seeds = false
skip-lint = false

[programs.localnet]
alyrasign = "FfEV5JPvSqajhtHQj2jUGvYz6GGNYkkMkHNhhE3rWqNp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./deployer-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" 