[toolchain]
anchor_version = "0.28.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
alyra_sign = "FfEV5JPvSqajhtHQj2jUGvYz6GGNYkkMkHNhhE3rWqNp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/"

[programs.localnet]
votee = "FQSjkWA6Sb6PcEJm693XsX9GETY7zhArPcPkkuLwdGws"

[programs.mainnet-beta]
alyra_sign = "FfEV5JPvSqajhtHQj2jUGvYz6GGNYkkMkHNhhE3rWqNp"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
